# Generated by Django 5.0.6 on 2024-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
