# Generated by Django 5.0.6 on 2024-08-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300, unique=True, verbose_name='Driver UID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Plate number')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is available')),
                ('last_paycheck', models.DateTimeField(verbose_name='Last paycheck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='accounts.user', verbose_name='User')),
            ],
        ),
    ]
