# Generated by Django 5.0.6 on 2024-08-05 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150, unique=True, verbose_name='Category UID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='provider.category', verbose_name='parent')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150, unique=True, verbose_name='Provider UID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is available')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='accounts.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150, unique=True, verbose_name='Product UID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('in_stock', models.PositiveSmallIntegerField(verbose_name='Stock')),
                ('image_path', models.CharField(max_length=100, verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='provider.category', verbose_name='Category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='provider.provider', verbose_name='Provider')),
            ],
        ),
    ]
